### PR TITLE
Objview, first pass.

### PR DESCRIPTION
**Pull request by sariths**
Hi @gmischler , This is my first, very raw, attempt at Objview. I have checked it on my Windows machine and it (hopefully) should work on other OS's too. I am not quite sure how to make the verbose thing work. 
4-6-2016 4-55-58 pm

I will be refining it based on my testing as well as your inputs in the coming days.

Sarith

PS: I wanted to add that even though it shows a whole bunch of commits (due to some github magic), there is only one file involved in this pull request.

### CODE REVIEW

**Comment by gmischler** [comment]
@sariths, that looks like a good start, with some more work waiting.

Here are the issues I found at a first glance. Don't worry about the
long list, most of the items are simple stuff.
- The "hashbang" (#!...) must be the very first line of the file for it to
  have the desired effect on unix systems.
- The traditional form of the encoding declaration is
  
  ```
  # -*- coding: utf-8 -*-
  ```
  
  Python will probably recognize it in either form (Python 3 already
  defaults to utf-8), but some editors may insist on the tradition.
  That also reminds me that I should probably add those to the other
  files.
- the `__revision__` attribute only makes sense if you actually use it
  somewhere (glaze.py writes it into the comment section of the
  output). However, we may later add an `# $Id: $` comment further up,
  once the files get checked into CVS (those markers are replaced with
  the info from the current commit by CVS).
- If you import Error from pyrad_proc, then your own definition of the
  same class further above serves no purpose (will be shadowed).
- The global definitions of commonOptions, useGl, radOptions, and
  glradOptions don't seem to serve any purpose, since you (correctly)
  only use the instance attributes of the same names.
- `os.path.isfile() and os.path.exists()` is redundant (can't be a file if it
  doesn't exist).
  You could also just let oconv complain if it doesn't find all the
  files, like the original does.
- You're not passing on any user provided options to rad and glrad.
  I assume you plan to add this?
- the call_xxx() methods are expecting a list of a command and
  arguments, not a string. It may partially work with a string, but
  the verbose output will look strange, and it will definitively fail
  when there are space characters in a filename path.
  It is easiest to just collect individual items into a list from the
  beginning. There's no point in e.g. first joining args.Radfiles into
  a single string, just to split the result again later.
- If you use argparse, then you don't need to check for the length of
  sys.argv yourself. Just set nargs to '+' instead of '*' for radfiles, and it
  will automatically complain if no file names have been given.
- The process invocation methods will recognize verbose mode if they
  find self.verbose set to True.
- You need to make sure that the tempfiles are deleted again after
  everything is finished.

**Comment by sariths** [comment]
Hi @gmischler , thank you for all the constructive comments. I guess a lot of it just me being sloppy! I will push an updated version with the relevant changes soon.

**Comment by sariths** [comment]
@gmischler, I have updated the file. I think I have addressed most of your comments. I haven't gotten around to checking this with Linux/Open GL yet. I will hopefully get it done sometime within the next five days or so.

Sarith

**Comment by gmischler** [comment]
@sariths, starts to look really good!

A few more points to consider, though:
- I recomment to wrap the call of self.run() into a "try" clause, and
  delete the tempfiles in the "finally" part. This garantees deletion
  no matter how the program exits, even if it crashes.
- This also means that instead of printErrorAndExit() you can use
  self.raise_on_error() from the process management library.
- You're still unnecessarily joining paths into a single string.
  Instead of:
  
  ```
    if sys.platform.startswith('win'):
        scene = " ".join(self.radFiles)
        if sys.platform.startswith('win'):
            allFileNames = [scene, octreeFile, lightsFile, rifFile, ambFile]
            scene, octreeFile, lightsFile, rifFile, ambFile = allFileNames 
  ```
  
  You might want to try something like this:
  
  ```
    if os.name == 'nt':
        self.radfiles = [s.replace('\\', '/') for s in self.radfiles]
        octreeFile, lightsFile, rifFile, ambFile = [s.replace('\\', '/')
                for s in (octreeFile, lightsFile, rifFile, ambFile)]
  ```
  
  And later create a seperate scene= entry in the rif file for each
  input file.
- Paths containing white space characters must be quoted in the rif
  file, or it will break them apart (at least for those variables that
  accept several items). It is simplest to just always quote them.
- On Windows, whichever rvu/rview version we're going to use will
  only have one default "device". I haven't checked qtrad, but I think it
  will actually ignore the -o option completely (as does winrview).
  The original always sets the default here, but we don't need to do that.
  We can pass the -o option (eg. appended to radOptions) only when the
  user actually specified it.
- It is much more efficient (and simple) to work with lists instead
  of concatenating strings.
  So you can replace:
  
  ```
    rifString = 'scene= %s\n' % scene
    rifString += 'EXPOSURE= 0.5\n'
    rifString += 'UP= %s\n' % (
            self.upDirection if self.upDirection else 'Z')
    ...
  ```
  
  with something like:
  
  ```
    riflines = ['scene= "%s"' % s for s in self.radfiles]
    riflines.append('EXPOSURE= 0.5')
    riflines.append('UP= %s' % (self.upDirection or 'Z'))
    ...
    with open(rifFile, 'w') as rifData:
        rifData.write('\n'.join(riflines) + '\n')
  ```
- The -s and -w options have similar, but still different effects,
  as have -V and -e. The original preserves those differences.
- The -V and -e options are only valid for rad in the original.
  In our case we should still accept -V for glrad (for printing our
  own verbose output), but just not pass it on.
- The error message for GL on windows is incorrect (in the original
  already). The problem is not OpenGL, that works on Windows just fine.
  It's just that glrad is an X11 application. More accurate would be:
  "Glrad is only available in an X11 environment".
- I recommend to split self.run() into several smaller methods, eg.:
  self.create_temp(), self.check_args(), and self.build_rif(), or something
  similar. If each method has its specific task, then they will be much
  easier to maintain later on.

**Comment by sariths** [comment]
@gmischler I was actually following the perl script till now. I just referred the original csh script on the CVS.
Many thanks for all the tips (and explaining the rationale behind them). I was thinking about a way to delete the tempdirectory regardless of the program outcome but didn't really think of wrapping the whole code within try-except. I will be pushing an update within a day or two.

**Comment by sariths** [comment]
Hi @gmischler, my apologies for net updating this file again. I have been tied up with work for the past few days ( I am a full-time PhD student). I should be able to get to this sometime within the 5-7 days.

Sarith

**Comment by gmischler** [comment]
Don't worry, we're not on a schedule here. What matters is the result, not whether it arrived a day earlier or later.

**Comment by sariths** [comment]
Hi @gmischler, I had a question regarding the `-s`|`-w` and `-V|-e` options in the c-shell script [here](https://github.com/NREL/Radiance/blob/master/src/util/objview.csh#L48-L52) and [here](https://github.com/NREL/Radiance/blob/master/src/util/objview.csh#L27-L30). I am not familiar with c-shell scripting to know for sure, but is there any additional logic being passed depending on which option is chosen in the script?

**Comment by gmischler** [comment]
It just appends the respective option to $opts, and for -e/-V sets $radopt. We'll only have to make a special case for -V with glrad, so we can still use it internally.

**Comment by sariths** [comment]
@gmischler , Thanks, reading these options from the RAD documentation makes a lot of things clearer. Anyway, this script keeps getting 'interesting'.. 

Regarding your comment:

> Paths containing white space characters must be quoted in the rif
> file, or it will break them apart (at least for those variables that
> accept several items). It is simplest to just always quote them.

If I pass something like `-N 8 C:\rm4\rad\room material.rad C:\rm4\rad\room_geometry.rad` (there is a space in the first file) to **argparse** it actually reads it as `'C:\\rm4\\rad\\room', 'material.rad', 'C:\\rm4\\rad\\room_geometry.rad'`. So, by the time it gets to the main part of the script the filenames are already broken, thus rendering the quotes-around-filename effort meaningless. I can fix this in a hacky way by doing something path checking. Do you recommend any straightforward ways for this ?

Secondly, although I am almost certain of this, I still want to check since there is no documentation.. in `def raise_on_error(self, actstr, e):` [here](https://github.com/gmischler/PyRad/blob/master/scripts/pyradlib/pyrad_proc.py#L24), does the actstr and e correspond to user-defined message and Exception respectively ?

**Comment by gmischler** [comment]
Paths with spaces need to be protected everywhere they appear, starting with the command line invoking the script itself.
`actstr` indicates what the script was trying to do in the form of "do something" (this is explained in the docstring of `call_one()`).
`e` is the specific error message, eg. the original exception raised, or a string of your own.

**Comment by sariths** [comment]
@gmischler I think I addressed most of your previous comments. The raise_on_error part still needs some work. I keep getting `Objview instance has no attribute '_strtypes'`  over [here](https://github.com/sariths/PyRad/blob/master/scripts/objview.py#L140-L142). Any idea why that might be ?

On the issue of splitting the main function into smaller ones, I have done that although I am not convinced if this is required for such a small script. I chose to add attributes instead of return values as it reduces code duplication by a little bit. 

Sarith

**Comment by gmischler** [comment]
The _strtypes issue was yet another bug in the library, that should be fixed now.

The run() method is currently about twice as tall as my screen. That's far beyond the threshold of easy readibility and certainly justifies splitting it up. Btw.: If it keeps things simpler, you can still use instance attributes to pass values around.

**Comment by sariths** [comment]
@gmischler The splitting part makes sense to me when you state it this way:

> ..The run() method is currently about twice as tall as my screen. That's far beyond the threshold of easy readibility..

I have shrunk the`run()`code in half by allocating the logic to two other functions. 

I think your last fix mostly solves the problem with `raise_on_error` except in cases where someone tries to suppy a string instead of an exception.. In here:

```
    def raise_on_error(self, actstr, e):
        try: self._strtypes
        except AttributeError: self.__configure_subprocess()
        if hasattr(e, 'strerror'): eb = e.strerror
        elif isinstance(e, self._strtypes): eb = e
        else: eb = e
        if isinstance(eb, type(b'')):
```

The attribute `._strtypes` only gets assigned to `self` through `call_one|call_two|call_many -- _parse_args -- __configure_subprocess`. Which implies that I if do something like `raise_on_error('write files', 'can't write to disk')` before calling a process through `call_one` etc. it will raise an attribute error for `elif isinstance(e, self._strtypes): eb = e`. 

I made it work through doing something like...

```
self.raise_on_error("Setting rad options",
                                IOError('','One among the following options :() '
                                           'are not compatible with Open GL'
                                        .format(",".join(radOptions))))
```

...which although hacky seems to do the job. I think I will able to avoid all the false-starts and missteps for the next script since I have somewhat of an idea of what your coding style is. Can we do **objpict** after this one is sorted out ?

I tried all the common options like w,e,-bv,Up etc. and they seem to work out fine. I have been meaning to test these in x11/Unix for a long time but haven't gotten around to that yet.

**Comment by gmischler** [comment]
What error do you get when you call raise_on_error() with a string?

My last fix was specifically supposed to solve that problem, by also calling
self.**configure_subprocess() when necessary.
Actually, this isn't the cleanest possible solution... I originally didn't think the module
would need initialization at all, which is why it doesn't have an __init**() method.
Maybe I should add one, and change all the scripts to use super().**init**().

I'm not sure this is my personal style you're learning. Some of my suggestions were
just based on design decision I had made for this project. And then there are general
recommendations for what is usually considered to be a "pythonic" style.

Objpic will be very easy after that, mostly because it's essentially a simplified version
of objview, with only one target program and no driver business.

**Comment by sariths** [comment]
@gmischler Your last commit actually did fix everything. I think I didn't have the latest file synchronized in my disk for some reason. Anyways, it's all working right now. If it looks fine, can you accept and close this pull request ?

Coming to coding-styles, I am involved in a few other projects and each lead developer(s)/curator(s)seem to have quirks/preferences of their own even while staying within the realm of what is considered Pythonic. I noticed that you don't seem to mind using functions with side effects (some people prefer functions to be treated as black-boxes) and also tend to use  EAFP quite a bit. For a novice programmer like myself, part of the attraction for me to get involved in such projects is to force myself to learn/adapt to such things. For example, I had never used argparse before working on the objview script. 

Once this pull-request is closed I will start working on objpict. I am going to get to testing these on unix some time and might make amendments in case I find any bugs.

**Comment by gmischler** [comment]
Pulled it. Thanks for the contribution @sariths !
I may make some minor tweaks and rearrangements, mostly to simplify stuff,
and remove some of the more redundant comments (if the purpose of the code is
unambiguous, "commenting the obvious" only confuses the reader).

Which coding style is appropriate often depends on context.
In a larger project I'd definitively put a lot more effort into avoiding side effects.
But within such a small and self-contained class that only makes calls to itself, there is
simply no point in being stubborn about it.
I actually do use EAFP, there simply wasn't much opportunity to do so in this project.
But I try to avoid it when it would involve "expensive" operations like creating files or invoking
external processes.
I haven't used argparse much myself either, mostly because I don't write commandline
scripts very often.

**Comment by sariths** [comment]
@gmischler, thanks for accepting the pull request. I figured out the cause of error that I was having with strtypes over [here](https://github.com/gmischler/PyRad/pull/4#issuecomment-213243619). The issue was that since the `pyradlib` package  sits inside the Raypath folder, which needs to be manually updated as it is outside the purview of the whole github stuff. I forgot to replace that file when I merged the repository with your updated `pyrad_proc.py` yesterday.

**Pull request merged**
